"use client";

import Image from "next/image";
import { ArrowUpRight, Check, ChevronDown, Clock3, Compass, ExternalLink, Heart, LocateFixed, MapPin, Search, ShieldCheck, SlidersHorizontal, Sparkles, Utensils } from "lucide-react";
import { useEffect, useMemo, useState } from "react";

type Place = { id: string; name: string; cuisine: string; neighborhood: string; distance: string; match: string; trust: number; source: string; verified: string; description: string; tags: string[]; photo?: boolean };

const places: Place[] = [
  { id: "soul-table", name: "소울 테이블", cuisine: "컨템퍼러리 한식", neighborhood: "서울 · 을지로", distance: "도보 6분", match: "취향 일치 94%", trust: 92, source: "공공 인허가 · 카카오 로컬", verified: "오늘 09:30 확인", description: "제철 식재료 중심의 코스와 단품. 조용한 저녁 식사에 잘 맞습니다.", tags: ["예약 추천", "혼밥 가능", "저녁"], photo: true },
  { id: "myeong-dong-noodle", name: "명동 면옥", cuisine: "국수 · 만두", neighborhood: "서울 · 명동", distance: "도보 9분", match: "취향 일치 88%", trust: 89, source: "공공 인허가 · 관광공사", verified: "어제 18:12 확인", description: "빠른 식사와 전통 메뉴를 찾을 때 적합한 지역 식당입니다.", tags: ["현지식", "빠른 식사", "가격 합리적"] },
  { id: "haneul-vegan", name: "하늘채 비건 다이닝", cuisine: "비건 · 퓨전", neighborhood: "서울 · 충무로", distance: "도보 12분", match: "취향 일치 83%", trust: 84, source: "카카오 로컬 · OSM", verified: "2일 전 확인", description: "채식 선택지가 명확하고 알레르기 요청을 사전에 안내합니다.", tags: ["비건", "알레르기 안내", "점심"] },
];
const filters = ["가까운 순", "조용한 곳", "혼밥", "현지식", "비건"];

export default function Home() {
  const [query, setQuery] = useState("조용한 한식 저녁");
  const [activeFilter, setActiveFilter] = useState("가까운 순");
  const [saved, setSaved] = useState<string[]>([]);
  const [location, setLocation] = useState("을지로입구역 주변");
  const [status, setStatus] = useState("위치 기반 추천 준비됨");
  const [selectedId, setSelectedId] = useState(places[0].id);

  useEffect(() => { const stored = window.localStorage.getItem("mise-saved-places"); if (stored) setSaved(JSON.parse(stored)); }, []);
  const results = useMemo(() => activeFilter === "비건" ? places.filter((place) => place.tags.includes("비건")) : activeFilter === "혼밥" ? places.filter((place) => place.tags.includes("혼밥 가능")) : places, [activeFilter]);
  function toggleSaved(id: string) { setSaved((current) => { const next = current.includes(id) ? current.filter((item) => item !== id) : [...current, id]; window.localStorage.setItem("mise-saved-places", JSON.stringify(next)); return next; }); }
  function useCurrentLocation() { if (!navigator.geolocation) { setStatus("이 브라우저에서는 위치 정보를 지원하지 않습니다."); return; } setStatus("현재 위치를 확인하는 중…"); navigator.geolocation.getCurrentPosition(({ coords }) => { setLocation(`현재 위치 · ${coords.latitude.toFixed(3)}, ${coords.longitude.toFixed(3)}`); setStatus("현재 위치를 반영했습니다. 실제 데이터 연결 후 주변 결과가 갱신됩니다."); }, () => setStatus("위치 권한이 필요합니다. 지역명을 직접 입력해도 됩니다."), { enableHighAccuracy: false, timeout: 7000 }); }

  return <main className="min-h-screen bg-[#f4f5f2] text-[#17221d]">
    <header className="sticky top-0 z-30 border-b border-[#dce2db] bg-[#f4f5f2]/92 backdrop-blur"><div className="mx-auto flex max-w-[1500px] items-center justify-between px-5 py-4 lg:px-8">
      <div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-[14px] bg-[#173e31] text-[#d8ff75] shadow-sm"><Utensils size={20} strokeWidth={2.4} /></div><div><p className="text-lg font-semibold tracking-[-0.04em]">mise</p><p className="text-xs text-[#65726b]">personal food finder</p></div></div>
      <div className="hidden items-center gap-2 text-sm text-[#55625b] sm:flex"><ShieldCheck size={16} className="text-[#277453]" />개인 데이터는 이 기기에만 저장</div>
      <button className="flex items-center gap-2 rounded-full bg-white px-3 py-2 text-sm font-medium shadow-sm ring-1 ring-[#dce2db]" aria-label="저장한 맛집 보기"><Heart size={16} className="fill-[#e25e54] text-[#e25e54]" /><span>{saved.length}</span></button>
    </div></header>

    <section className="mx-auto max-w-[1500px] px-5 pb-5 pt-7 lg:px-8"><div className="grid gap-6 xl:grid-cols-[minmax(0,1.35fr)_minmax(420px,0.65fr)] xl:items-end"><div><div className="mb-3 flex items-center gap-2 text-sm font-medium text-[#277453]"><span className="h-2 w-2 rounded-full bg-[#83c98a]" />신뢰 가능한 장소를 먼저 보여드려요</div><h1 className="max-w-3xl text-3xl font-semibold leading-[1.08] tracking-[-0.055em] sm:text-5xl">오늘의 식사는, <span className="text-[#277453]">근거</span>와 함께 고르세요.</h1></div><p className="max-w-xl border-l-2 border-[#c4d9c9] pl-4 text-sm leading-6 text-[#5c6962] sm:text-base">공공 인허가, 지역 검색, 오픈 지도 데이터를 교차 확인해 결과별로 출처와 마지막 확인 시점을 표시합니다.</p></div>
      <div className="mt-7 rounded-[24px] border border-[#d9e1d8] bg-white p-3 shadow-[0_16px_40px_rgba(34,57,43,0.07)]"><div className="grid gap-3 lg:grid-cols-[1.05fr_1.35fr_auto]">
        <label className="flex min-w-0 items-center gap-3 rounded-[16px] bg-[#f1f5ef] px-4 py-3"><MapPin size={19} className="shrink-0 text-[#277453]" /><input value={location} onChange={(event) => setLocation(event.target.value)} className="min-w-0 flex-1 bg-transparent text-sm font-medium outline-none" aria-label="검색 지역" /><ChevronDown size={16} className="text-[#77847c]" /></label>
        <label className="flex min-w-0 items-center gap-3 rounded-[16px] bg-[#f1f5ef] px-4 py-3"><Search size={19} className="shrink-0 text-[#6a756f]" /><input value={query} onChange={(event) => setQuery(event.target.value)} className="min-w-0 flex-1 bg-transparent text-sm outline-none" aria-label="원하는 식당 조건" /><Sparkles size={17} className="text-[#82974c]" /></label>
        <button onClick={() => setStatus(`“${query}” 조건으로 결과를 정렬했습니다.`)} className="rounded-[16px] bg-[#173e31] px-6 py-3.5 text-sm font-semibold text-white transition hover:bg-[#23513f]">탐색하기</button>
      </div><div className="mt-3 flex flex-wrap items-center justify-between gap-3 px-1 pb-1"><button onClick={useCurrentLocation} className="flex items-center gap-2 text-sm font-medium text-[#277453] hover:text-[#173e31]"><LocateFixed size={16} />현재 위치 사용</button><p aria-live="polite" className="text-xs text-[#738078]">{status}</p></div></div>
    </section>

    <section className="mx-auto grid max-w-[1500px] gap-5 px-5 pb-10 lg:px-8 xl:grid-cols-[minmax(430px,0.94fr)_minmax(400px,1.06fr)]"><div className="min-w-0"><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div className="flex flex-wrap gap-2" aria-label="검색 필터">{filters.map((filter) => <button key={filter} onClick={() => setActiveFilter(filter)} className={`rounded-full px-3.5 py-2 text-sm font-medium transition ${activeFilter === filter ? "bg-[#173e31] text-white" : "bg-white text-[#59675f] ring-1 ring-[#dce2db] hover:bg-[#edf2ec]"}`}>{filter}</button>)}</div><button className="flex items-center gap-2 text-sm font-medium text-[#526057]"><SlidersHorizontal size={16} />필터</button></div>
      <div className="mb-4 flex items-end justify-between"><div><p className="text-sm text-[#69766f]">{location}</p><h2 className="mt-1 text-xl font-semibold tracking-[-0.04em]">추천 결과 <span className="text-[#277453]">{results.length}</span>곳</h2></div><p className="text-xs text-[#7a867f]">출처가 2개 이상인 곳 우선</p></div>
      <div className="space-y-3">{results.map((place, index) => <article key={place.id} onClick={() => setSelectedId(place.id)} className={`group cursor-pointer overflow-hidden rounded-[22px] border bg-white transition ${selectedId === place.id ? "border-[#7fba8e] shadow-[0_10px_30px_rgba(27,80,51,0.09)]" : "border-[#dce2db] hover:border-[#b7cdb9]"}`}><div className="flex gap-4 p-4">{place.photo ? <div className="relative hidden h-28 w-28 shrink-0 overflow-hidden rounded-[16px] sm:block"><Image src="/mise-featured-dish.png" alt="소울 테이블의 제철 한식 요리" fill sizes="112px" className="object-cover" /></div> : <div className={`hidden h-28 w-28 shrink-0 place-items-center rounded-[16px] sm:grid ${index === 1 ? "bg-[#f8eddd] text-[#c87839]" : "bg-[#eaf2e8] text-[#4d8b64]"}`}><Utensils size={28} /></div>}<div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-3"><div><div className="flex flex-wrap items-center gap-x-2 gap-y-1"><h3 className="text-lg font-semibold tracking-[-0.035em]">{place.name}</h3><span className="rounded-full bg-[#eaf5e9] px-2 py-0.5 text-xs font-semibold text-[#277453]">{place.match}</span></div><p className="mt-1 text-sm text-[#68766e]">{place.cuisine} · {place.neighborhood} · {place.distance}</p></div><button onClick={(event) => { event.stopPropagation(); toggleSaved(place.id); }} className="rounded-full p-2 text-[#7d8882] hover:bg-[#f2f5f1]" aria-label={`${place.name} 저장`}><Heart size={18} className={saved.includes(place.id) ? "fill-[#e25e54] text-[#e25e54]" : ""} /></button></div><p className="mt-3 line-clamp-2 text-sm leading-5 text-[#526057]">{place.description}</p><div className="mt-3 flex flex-wrap items-center gap-2">{place.tags.map((tag) => <span key={tag} className="rounded-md bg-[#f1f4f0] px-2 py-1 text-xs text-[#657169]">{tag}</span>)}</div></div></div><footer className="flex flex-wrap items-center justify-between gap-2 border-t border-[#edf0ec] bg-[#fbfcfa] px-4 py-2.5 text-xs"><span className="flex items-center gap-1.5 font-medium text-[#277453]"><ShieldCheck size={14} />신뢰도 {place.trust}/100</span><span className="flex items-center gap-1.5 text-[#69766f]"><Check size={14} className="text-[#5d9a6c]" />{place.source}</span><span className="flex items-center gap-1.5 text-[#7b8780]"><Clock3 size={13} />{place.verified}</span></footer></article>)}</div>
    </div>
    <aside className="min-h-[540px] overflow-hidden rounded-[26px] border border-[#cbd7cb] bg-[#dbe7d8] shadow-[0_16px_40px_rgba(37,80,49,0.1)]"><div className="relative h-full min-h-[540px] overflow-hidden bg-[radial-gradient(circle_at_20%_15%,rgba(255,255,255,.84)_0_2px,transparent_2px),linear-gradient(122deg,transparent_0_38%,rgba(251,244,221,.72)_38%_44%,transparent_44%_100%),linear-gradient(25deg,transparent_0_45%,rgba(255,255,255,.58)_45%_49%,transparent_49%_100%),linear-gradient(#d7e6d4,#edf3e7)] [background-size:22px_22px,100%_100%,100%_100%,100%_100%]"><div className="absolute left-[14%] top-[6%] h-[88%] w-9 rotate-[21deg] rounded-full bg-[#94b9dd]/55 blur-[1px]" /><div className="absolute right-[18%] top-[12%] h-[70%] w-2 rotate-[52deg] rounded-full bg-white/80" /><div className="absolute inset-x-5 top-5 flex items-center justify-between"><div className="rounded-xl bg-white/92 px-3 py-2 text-sm font-medium shadow-sm">서울 · 중구</div><button className="grid h-10 w-10 place-items-center rounded-xl bg-white/92 text-[#285340] shadow-sm" aria-label="지도 중심으로 이동"><Compass size={19} /></button></div><div className="absolute left-[31%] top-[42%] grid h-12 w-12 place-items-center rounded-full border-4 border-white bg-[#173e31] text-white shadow-lg"><MapPin size={21} fill="currentColor" /></div>{[[64, 29, "#d96e52"], [72, 52, "#277453"], [50, 64, "#d6963f"], [23, 68, "#277453"], [78, 73, "#d96e52"]].map(([left, top, color], index) => <div key={index} className="absolute grid h-9 w-9 place-items-center rounded-full border-2 border-white text-white shadow-md" style={{ left: `${left}%`, top: `${top}%`, backgroundColor: color as string }}><Utensils size={15} /></div>)}<div className="absolute inset-x-5 bottom-5 rounded-[20px] bg-white/95 p-4 shadow-[0_10px_25px_rgba(22,48,33,.13)] backdrop-blur"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[0.1em] text-[#66816d]">선택한 장소</p><h3 className="mt-1 text-lg font-semibold">{places.find((place) => place.id === selectedId)?.name}</h3><p className="mt-1 text-sm text-[#657169]">출처와 확인일을 먼저 확인하세요.</p></div><button className="grid h-9 w-9 place-items-center rounded-full bg-[#eaf3e8] text-[#277453]" aria-label="장소 상세 보기"><ArrowUpRight size={18} /></button></div><div className="mt-3 flex gap-2"><button className="flex flex-1 items-center justify-center gap-2 rounded-xl bg-[#173e31] px-3 py-2.5 text-sm font-semibold text-white"><MapPin size={15} />길찾기</button><button className="flex items-center gap-2 rounded-xl border border-[#dce2db] px-3 py-2.5 text-sm font-medium text-[#45554b]"><ExternalLink size={15} />출처</button></div></div></div></aside>
    </section>
  </main>;
}
